Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your collaborators below:

In [1]:
COLLABORATORS = ""

---

<div class="alert alert-danger">
As a reminder, one of the prerequisites for this course if programming experience, especially in Python. If you do not have experience in Python specifically, we <b>strongly</b> recommend you go through the <a href="http://www.codecademy.com/tracks/python">Codecademy Python course</a> as soon as possible to brush up on the basics of Python.
</div>

<div class="alert alert-warning">Before going through this notebook, you may want to take a quick look at [7 - Debugging.ipynb](7 - Debugging.ipynb) if you haven't already for some tips on debugging your code when you get stuck.</div>

In [2]:
import numpy as np

This is a final exercise to get you comfortable working with numpy arrays. In this exercise, we're going to be programmatically constructing truth tables from boolean vectors. A *truth table* lists all possible Boolean outputs for the given inputs. For example, an AND truth table would look like this:

<table class="table table-striped" style="width: 5em;">
  <thead>
    <tr>
      <th>$a$</th>
      <th>$b$</th>
      <th>$a\wedge b$
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <th>0</th>
      <th>0</th>
    </tr>
    <tr>
      <th>0</th>
      <th>1</th>
      <th>0</th>
    </tr>
    <tr>
      <th>1</th>
      <th>0</th>
      <th>0</th>
    </tr>
    <tr>
      <th>1</th>
      <th>1</th>
      <th>1</th>
    </tr>
  </tbody>
</table>

Each row corresponds to different values of $a$ (first column) and $b$ (second column), and the third column corresponds to whatever $a\wedge b$ is.

We can represent the different values of $a$ and $b$ using boolean arrays in numpy:

In [3]:
# create boolean vectors a and b
a = np.array([0, 0, 1, 1], dtype=bool)
b = np.array([0, 1, 0, 1], dtype=bool)

You can compute the logical AND of `a` and `b` using the `&` operator (and the symbols for the Boolean operations OR and NOT are `|` and `~`, respectively).

In [4]:
# run this cell to see what happens when we use the & operator on a and b
a & b

array([False, False, False,  True], dtype=bool)

<div class="alert alert-success">Complete the functions below to produce truth tables for AND, OR, and NOT. Be sure to use the logical operators discussed above in your solution!</div>

----

## Part A: AND Table (1.25 points)

In [5]:
def and_table(a, b):
    """
    Takes two boolean vectors, `a` and `b`, and returns an AND truth
    table consisting three columns: a, b, and (a AND b). If you forget
    how an AND operator works, see the Wikipedia page on logical
    conjunctions: https://en.wikipedia.org/wiki/Logical_conjunction

    Parameters
    ----------
    a : boolean array with shape (n,)
    b : boolean array with shape (n,)

    Returns
    -------
    boolean array with shape (n, 3)

    """
    n = a.size 
    n_array = np.zeros((n, 3))
    n_array[:, 0] = a
    n_array[:, 1] = b
    n_array[:, 2] = a&b
    return n_array

After you have implemented `and_table` above, you can try running it with inputs `a` and `b`:

In [6]:
and_table(a, b)

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  1.]])

In [7]:
# add your own test cases in this cell!


In [8]:
"""Check whether and_table returns an array with the correct shape for random inputs."""
from nose.tools import assert_equal
for i in range(10):
    # randomize the vector length
    n = np.random.randint(1, 11)
    # randomly generate binary vectors
    v1 = np.random.randint(0, 2, n).astype(bool)
    v2 = np.random.randint(0, 2, n).astype(bool)
    # check the shape of the AND table
    assert_equal(and_table(v1, v2).shape, (n, 3))

print("Success!")

Success!


In [9]:
"""Check whether and_table returns the correct answer for two particular vectors."""
from numpy.testing import assert_array_equal
# create the two vectors
v1 = np.array([0, 0, 1, 1], dtype=bool)
v2 = np.array([0, 1, 0, 1], dtype=bool)

# check (v1 AND v1)
v11 = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]], dtype=bool)
assert_array_equal(and_table(v1, v1), v11)

# check (v1 AND v2)
v12 = np.array([[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]], dtype=bool)
assert_array_equal(and_table(v1, v2), v12)

# check (v2 AND v1)
v21 = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0], [1, 1, 1]], dtype=bool)
assert_array_equal(and_table(v2, v1), v21)

# check (v2 AND v2)
v22 = np.array([[0, 0, 0], [1, 1, 1], [0, 0, 0], [1, 1, 1]], dtype=bool)
assert_array_equal(and_table(v2, v2), v22)

print("Success!")

Success!


----

## Part B: OR Table (1.25 points)

In [10]:
def or_table(a, b):
    """
    Takes two boolean vectors, `a` and `b`, and returns an OR truth
    table consisting three columns: a, b, and (a OR b).

    Parameters
    ----------
    a : boolean array with shape (n,)
    b : boolean array with shape (n,)

    Returns
    -------
    boolean array with shape (n, 3)

    """
    n = a.size 
    n_array = np.zeros((n, 3))
    n_array[:, 0] = a
    n_array[:, 1] = b
    n_array[:, 2] = np.logical_or(a,b)
    return n_array

After you have implemented `or_table` above, you can try running it with inputs `a` and `b`:

In [11]:
or_table(a, b)

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
# add your own test cases in this cell!


In [13]:
"""Check whether or_table returns an array with the correct shape for random inputs."""
for i in range(10):
    # randomize the vector length
    n = np.random.randint(1, 11)
    # randomly generate binary vectors
    v1 = np.random.randint(0, 2, n).astype(bool)
    v2 = np.random.randint(0, 2, n).astype(bool)
    # check the shape of the OR table
    assert_equal(or_table(v1, v2).shape, (n, 3))

print("Success!")

Success!


In [14]:
"""Check whether or_table returns the correct answer for two particular vectors."""
# create the two vectors
v1 = np.array([0, 0, 1, 1], dtype=bool)
v2 = np.array([0, 1, 0, 1], dtype=bool)

# check (v1 OR v1)
v11 = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]], dtype=bool)
assert_array_equal(or_table(v1, v1), v11)

# check (v1 OR v2)
v12 = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]], dtype=bool)
assert_array_equal(or_table(v1, v2), v12)

# check (v2 OR v1)
v21 = np.array([[0, 0, 0], [1, 0, 1], [0, 1, 1], [1, 1, 1]], dtype=bool)
assert_array_equal(or_table(v2, v1), v21)

# check (v2 OR v2)
v22 = np.array([[0, 0, 0], [1, 1, 1], [0, 0, 0], [1, 1, 1]], dtype=bool)
assert_array_equal(or_table(v2, v2), v22)

print("Success!")

Success!


----

## Part C: NOT Table (1.25 points)

In [15]:
def not_table(a):
    """
    Takes one boolean vector, `a`, and returns a NOT truth
    table consisting two columns: a and (NOT a).

    Parameters
    ----------
    a : boolean array with shape (n,)

    Returns
    -------
    boolean array with shape (n, 2)

    """
    n = a.size 
    n_array = np.zeros((n, 2))
    n_array[:, 0] = a
    n_array[:, 1] = np.logical_not(a,a)
    return n_array

After you have implemented `not_table` above, you can try running it with inputs `a` and `b`:

In [16]:
not_table(a)

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [17]:
# add your own test cases in this cell!


In [18]:
"""Check whether or_table returns an array with the correct shape for random inputs."""
for i in range(10):
    # randomize the vector length
    n = np.random.randint(1, 11)
    # randomly generate a binary vector
    v = np.random.randint(0, 2, n).astype(bool)
    # check the shape of the OR table
    assert_equal(not_table(v).shape, (n, 2))

print("Success!")

Success!


In [19]:
"""Check whether or_table returns the correct answer for two particular vectors."""
# create the two vectors
v1 = np.array([0, 0, 1, 1], dtype=bool)
v2 = np.array([0, 1, 0, 1], dtype=bool)

# check (NOT v1)
vn1 = np.array([[0, 1], [0, 1], [1, 0], [1, 0]], dtype=bool)
assert_array_equal(not_table(v1), vn1)

# check (NOT v2)
vn2 = np.array([[0, 1], [1, 0], [0, 1], [1, 0]], dtype=bool)
assert_array_equal(not_table(v2), vn2)

print("Success!")

Success!


---

Before turning this problem in remember to do the following steps:

1. **Restart the kernel** (Kernel$\rightarrow$Restart)
2. **Run all cells** (Cell$\rightarrow$Run All)
3. **Save** (File$\rightarrow$Save and Checkpoint)

<div class="alert alert-danger">After you have completed these three steps, ensure that the following cell has printed "No errors". If it has <b>not</b> printed "No errors", then your code has a bug in it and has thrown an error! Make sure you fix this error before turning in your problem set.</div>

In [20]:
print("No errors!")

No errors!
